source 'https://rubygems.org'
require 'rubygems'

gem 'nokogiri'
gem 'uuidtools'
gem 'ox'
gem 'json'
gem 'httparty'
gem 'thor'
gem 'ssl_certifier'
gem 'awesome_print'
gem 'gmail'
gem 'recursive-open-struct'
gem 'colorize'
gem 'viewpoint'
gem 'icloud', :git => 'git://github.com/adammck/ruby-icloud.git'